### ISSUE TITLE
请问，使用了 crack.js生成的文件和源混淆文件是一样的？crack.js现在还可以使用吗？

### ISSUE THREAD

**Issue by wenchuanli** [jscck/crack.js#1]

**Comment by mdys** [comment]
老大 ,能给明确说下使用方法吗? 执行之后获取的结果和源文件是一样的. 而且还报错了. 感谢老大指点!
`[root@localhost crack.js]# node crack.js
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn prettier-eslint ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3`

源文件如下 
`var _0xbe99=['sessionStorage','site','contentTabs','ifameTabs','configs','components','init','Breakpoints','toastr','notifyFn','extend','_dequeue','_trigger','before.run','complete','after.run','shift','call','isArray','_queue','each','isFunction','unshift','undefined','#admui-pageContent','.app','.page-aside','hasClass','open','toggleClass','click','.page-aside-switch','pageAside','stopPropagation','top','document','parentFrame','ctx','storage'];(function(_0x32afe5,_0x517ff6){var _0x3f8eb9=function(_0xb9a235){while(--_0xb9a235){_0x32afe5['push'](_0x32afe5['shift']());}};_0x3f8eb9(++_0x517ff6);}(_0xbe99,0xe5));var _0x9be9=function(_0x4d7585,_0xadf476){_0x4d7585=_0x4d7585-0x0;var _0x509c1a=_0xbe99[_0x4d7585];return _0x509c1a;};(function(_0x3840ae,_0x27f112,_0x27fb95){'use strict';_0x27fb95['parentFrame']=_0x27fb95(_0x3840ae[_0x9be9('0x0')][_0x9be9('0x1')]);var _0x3445f5=_0x3840ae[_0x9be9('0x2')]=_0x3840ae['top'];_0x27fb95[_0x9be9('0x3')]=_0x3445f5['$'][_0x9be9('0x3')];_0x27fb95['colors']=_0x3445f5['$']['colors'];_0x27fb95['po']=_0x3445f5['$']['po'];_0x27fb95[_0x9be9('0x4')]=_0x3445f5['$'][_0x9be9('0x4')];_0x27fb95[_0x9be9('0x5')]=_0x3445f5['$'][_0x9be9('0x5')];_0x27fb95[_0x9be9('0x6')]=_0x3445f5['$'][_0x9be9('0x6')];_0x27fb95[_0x9be9('0x6')][_0x9be9('0x7')][_0x9be9('0x8')](_0x27f112);_0x27fb95[_0x9be9('0x9')]=_0x3445f5['$'][_0x9be9('0x9')];_0x3445f5['$'][_0x9be9('0xa')][_0x9be9('0xb')](_0x27f112,_0x3840ae);_0x3840ae[_0x9be9('0xc')]=_0x3445f5[_0x9be9('0xc')];_0x3840ae[_0x9be9('0xd')]=_0x3445f5[_0x9be9('0xd')];_0x3840ae['notifyFn']=_0x3445f5['$'][_0x9be9('0xe')];var _0x12ede7=_0x12ede7||{};_0x27fb95[_0x9be9('0xf')](_0x12ede7,{'_queue':{'prepare':[],'run':[],'complete':[]},'run':function(){var _0x2c9ef2=this;this[_0x9be9('0x10')]('prepare',function(){_0x2c9ef2[_0x9be9('0x11')](_0x9be9('0x12'),_0x2c9ef2);});this[_0x9be9('0x10')]('run',function(){_0x2c9ef2[_0x9be9('0x10')](_0x9be9('0x13'),function(){_0x2c9ef2[_0x9be9('0x11')](_0x9be9('0x14'),_0x2c9ef2);});});},'_dequeue':function(_0x13a055,_0x5287d9){var _0x1acff2=this,_0x1cbff7=this['_getQueue'](_0x13a055),_0xa51592=_0x1cbff7[_0x9be9('0x15')](),_0x5f2612=function(){_0x1acff2[_0x9be9('0x10')](_0x13a055,_0x5287d9);};if(_0xa51592){_0xa51592[_0x9be9('0x16')](this,_0x5f2612);}else if(_0x27fb95['isFunction'](_0x5287d9)){_0x5287d9['call'](this);}},'_getQueue':function(_0x440431){if(!_0x27fb95[_0x9be9('0x17')](this[_0x9be9('0x18')][_0x440431])){this[_0x9be9('0x18')][_0x440431]=[];}return this[_0x9be9('0x18')][_0x440431];},'extend':function(_0x3761c7){_0x27fb95[_0x9be9('0x19')](this[_0x9be9('0x18')],function(_0x28f055,_0x16c01e){if(_0x27fb95[_0x9be9('0x1a')](_0x3761c7[_0x28f055])){_0x16c01e[_0x9be9('0x1b')](_0x3761c7[_0x28f055]);delete _0x3761c7[_0x28f055];}});_0x27fb95['extend'](this,_0x3761c7);return this;},'_trigger':function(_0x33d3a5,_0x59d14d,_0x2d543d){if(typeof _0x33d3a5===_0x9be9('0x1c')){return;}if(typeof _0x2d543d===_0x9be9('0x1c')){_0x2d543d=_0x27fb95(_0x9be9('0x1d'));}_0x2d543d['trigger'](_0x33d3a5+_0x9be9('0x1e'),_0x59d14d);}});var _0xfb4266={'pageAside':function(){var _0x8a7130=_0x27fb95(_0x9be9('0x1f')),_0x42a486=_0x8a7130[_0x9be9('0x20')](_0x9be9('0x21'));_0x8a7130[_0x9be9('0x22')](_0x9be9('0x21'),!_0x42a486);},'run':function(_0x27be52){var _0x5c5858=this;_0x27fb95(_0x27f112)['on'](_0x9be9('0x23'),_0x9be9('0x24'),function(_0x26db60){_0x5c5858[_0x9be9('0x25')]();_0x26db60[_0x9be9('0x26')]();});_0x27be52();}};_0x3840ae['App']=_0x27fb95[_0x9be9('0xf')]({},_0x12ede7);App[_0x9be9('0xf')](_0xfb4266);}(window,document,jQuery));`

**Comment by icai** [comment]
`_0x27c8` 批量替换一下 还有 44 行字典函数
